# Generated by Django 5.0.3 on 2024-03-07 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="color",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="color",
                to="home.color",
            ),
            preserve_default=False,
        ),
    ]
