# Generated by Django 5.0.3 on 2024-03-07 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_person_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="color",
                to="home.color",
            ),
        ),
    ]
